jenkins:
  systemMessage: "Jenkins configured using CasC."
  authorizationStrategy: "loggedInUsersCanDoAnything"
  numExecutors: 2
  mode: NORMAL
  disableRememberMe: false
  crumbIssuer:
    standard:
      excludeClientIPFromCrumb: true
  scmCheckoutRetryCount: 3
  securityRealm:
    local:
      allowsSignup: false
      users:
      - id: "admin"
        password: "admin"
unclassified:
  gitSCM:
    createAccountBasedOnEmail: true
    globalConfigEmail: "Jenkins@gft.com"
    globalConfigName: "Jenkins"
    showEntireCommitSummaryInChanges: false
    useExistingAccountWithSameEmail: true
tool:
  dockerTool:
    installations:
    - name: "docker"
      properties:
      - installSource:
          installers:
          - fromDocker:
              version: "19.03.9"
  git:
    installations:
    - home: "git"
      name: "Default"
jobs:
- script: >
    job('Seed All') {
      parameters {
        stringParam('REPO', 'https://github.com/tranquilitybase-io/tb-houston-orchestration/', 'The branch where Jenins is stored')
        stringParam('BRANCH', 'master', 'The branch (used for testing)')
      }
      triggers {
        cron("H/15 * * * *")
      }
      scm {
        git {
          remote {
            url 'https://github.com/tranquilitybase-io/tb-houston-orchestration.git'
          }
        }
      }
      steps {
        dsl {
          external('jenkins/Jenkins Cluster/gcp/Docker-image/Docker-files/jobs/*.groovy')  
       // default behavior
       // removeAction('IGNORE')      
          removeAction('DELETE')
        }
      }
    }
